pyuic5  ui\addellipse.ui -o  ..\ui_addellipse.py
pyuic5  ui\addrectangle.ui -o  ..\ui_addrectangle.py
pyuic5  ui\advancedsetupinspections.ui -o  ..\ui_advancedsetupinspections.py
pyuic5  ui\advancedsimulationsetup.ui -o  ..\ui_advancedsimulationsetup.py
pyuic5  ui\boundarysetup.ui -o  ..\ui_boundarysetup.py
pyuic5  ui\checksimulation.ui -o  ..\ui_checksimulation.py
pyuic5  ui\generatevideo.ui -o  ..\ui_generatevideo.py
pyuic5  ui\linearscansetup.ui -o  ..\ui_linearscansetup.py
pyuic5  ui\loadimagemainwindow.ui -o  ..\ui_loadimagemainwindow.py
pyuic5  ui\mainwindow.ui -o  ..\ui_mainwindow.py
pyuic5  ui\materiallibrary.ui -o  ..\ui_materiallibrary.py
pyuic5  ui\materialsetup.ui -o  ..\ui_materialsetup.py
pyuic5  ui\newscenario.ui -o  ..\ui_newscenario.py
pyuic5  ui\runsimulation.ui -o  ..\ui_runsimulation.py
pyuic5  ui\signalsetup.ui -o  ..\ui_signalsetup.py
pyuic5  ui\simulationsetup.ui -o  ..\ui_simulationsetup.py
pyuic5  ui\singlelaunchsetup.ui -o  ..\ui_singlelaunchsetup.py
pyuic5  ui\threephasemodeldrycase.ui -o  ..\ui_threephasemodeldrycase.py
pyuic5  ui\threephasemodelimmersioncase.ui -o  ..\ui_threephasemodelimmersioncase.py
pyuic5  ui\tomographysetup.ui -o  ..\ui_tomographysetup.py
pyuic5  ui\twophasemodeldrycase.ui -o  ..\ui_twophasemodeldrycase.py
pyuic5  ui\twophasemodelimmersioncase.ui -o  ..\ui_twophasemodelimmersioncase.py
