# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addrectangle.ui'
#
# Created: Tue Jul 29 23:02:06 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_addRectangleDialog(object):
    def setupUi(self, addRectangleDialog):
        addRectangleDialog.setObjectName("addRectangleDialog")
        addRectangleDialog.setWindowModality(QtCore.Qt.WindowModal)
        addRectangleDialog.resize(220, 258)
        addRectangleDialog.setMinimumSize(QtCore.QSize(220, 258))
        addRectangleDialog.setMaximumSize(QtCore.QSize(220, 258))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rectangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addRectangleDialog.setWindowIcon(icon)
        addRectangleDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        addRectangleDialog.setSizeGripEnabled(False)
        addRectangleDialog.setModal(False)
        self.buttonBox = QtGui.QDialogButtonBox(addRectangleDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 220, 191, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtGui.QWidget(addRectangleDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 181, 181))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.centerXLabel = QtGui.QLabel(self.formLayoutWidget)
        self.centerXLabel.setObjectName("centerXLabel")
        self.gridLayout.addWidget(self.centerXLabel, 0, 0, 1, 1)
        self.centerXLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.centerXLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.centerXLineEdit.setMaximumSize(QtCore.QSize(80, 21))
        self.centerXLineEdit.setObjectName("centerXLineEdit")
        self.gridLayout.addWidget(self.centerXLineEdit, 0, 1, 1, 1)
        self.centerYLabel = QtGui.QLabel(self.formLayoutWidget)
        self.centerYLabel.setObjectName("centerYLabel")
        self.gridLayout.addWidget(self.centerYLabel, 1, 0, 1, 1)
        self.centerYLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.centerYLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.centerYLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.centerYLineEdit.setObjectName("centerYLineEdit")
        self.gridLayout.addWidget(self.centerYLineEdit, 1, 1, 1, 1)
        self.widthLabel = QtGui.QLabel(self.formLayoutWidget)
        self.widthLabel.setObjectName("widthLabel")
        self.gridLayout.addWidget(self.widthLabel, 2, 0, 1, 1)
        self.widthLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.widthLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.widthLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.widthLineEdit.setObjectName("widthLineEdit")
        self.gridLayout.addWidget(self.widthLineEdit, 2, 1, 1, 1)
        self.heightLabel = QtGui.QLabel(self.formLayoutWidget)
        self.heightLabel.setObjectName("heightLabel")
        self.gridLayout.addWidget(self.heightLabel, 3, 0, 1, 1)
        self.heightLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.heightLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.heightLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.heightLineEdit.setObjectName("heightLineEdit")
        self.gridLayout.addWidget(self.heightLineEdit, 3, 1, 1, 1)
        self.angleLabel = QtGui.QLabel(self.formLayoutWidget)
        self.angleLabel.setObjectName("angleLabel")
        self.gridLayout.addWidget(self.angleLabel, 4, 0, 1, 1)
        self.angleLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.angleLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.angleLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.angleLineEdit.setObjectName("angleLineEdit")
        self.gridLayout.addWidget(self.angleLineEdit, 4, 1, 1, 1)
        self.labelLabel = QtGui.QLabel(self.formLayoutWidget)
        self.labelLabel.setObjectName("labelLabel")
        self.gridLayout.addWidget(self.labelLabel, 5, 0, 1, 1)
        self.labelSpinBox = QtGui.QSpinBox(self.formLayoutWidget)
        self.labelSpinBox.setMaximum(240)
        self.labelSpinBox.setSingleStep(40)
        self.labelSpinBox.setObjectName("labelSpinBox")
        self.gridLayout.addWidget(self.labelSpinBox, 5, 1, 1, 1)

        self.retranslateUi(addRectangleDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), addRectangleDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), addRectangleDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(addRectangleDialog)

    def retranslateUi(self, addRectangleDialog):
        addRectangleDialog.setWindowTitle(QtGui.QApplication.translate("addRectangleDialog", "Add Rectangle", None, QtGui.QApplication.UnicodeUTF8))
        addRectangleDialog.setToolTip(QtGui.QApplication.translate("addRectangleDialog", "Add Rectangle", None, QtGui.QApplication.UnicodeUTF8))
        addRectangleDialog.setStatusTip(QtGui.QApplication.translate("addRectangleDialog", "Add Rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.centerXLabel.setText(QtGui.QApplication.translate("addRectangleDialog", "Center X (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.centerXLineEdit.setToolTip(QtGui.QApplication.translate("addRectangleDialog", "Center X", None, QtGui.QApplication.UnicodeUTF8))
        self.centerXLineEdit.setStatusTip(QtGui.QApplication.translate("addRectangleDialog", "Center X", None, QtGui.QApplication.UnicodeUTF8))
        self.centerYLabel.setText(QtGui.QApplication.translate("addRectangleDialog", "Center Y (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.centerYLineEdit.setToolTip(QtGui.QApplication.translate("addRectangleDialog", "Center Y", None, QtGui.QApplication.UnicodeUTF8))
        self.centerYLineEdit.setStatusTip(QtGui.QApplication.translate("addRectangleDialog", "Center Y", None, QtGui.QApplication.UnicodeUTF8))
        self.widthLabel.setText(QtGui.QApplication.translate("addRectangleDialog", "Width (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.widthLineEdit.setToolTip(QtGui.QApplication.translate("addRectangleDialog", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.widthLineEdit.setStatusTip(QtGui.QApplication.translate("addRectangleDialog", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.heightLabel.setToolTip(QtGui.QApplication.translate("addRectangleDialog", "Add Rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.heightLabel.setStatusTip(QtGui.QApplication.translate("addRectangleDialog", "Add Rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.heightLabel.setText(QtGui.QApplication.translate("addRectangleDialog", "Height (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.heightLineEdit.setToolTip(QtGui.QApplication.translate("addRectangleDialog", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.heightLineEdit.setStatusTip(QtGui.QApplication.translate("addRectangleDialog", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.angleLabel.setText(QtGui.QApplication.translate("addRectangleDialog", "Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.angleLineEdit.setToolTip(QtGui.QApplication.translate("addRectangleDialog", "Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.angleLineEdit.setStatusTip(QtGui.QApplication.translate("addRectangleDialog", "Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLabel.setText(QtGui.QApplication.translate("addRectangleDialog", "Label", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSpinBox.setToolTip(QtGui.QApplication.translate("addRectangleDialog", "Label", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSpinBox.setStatusTip(QtGui.QApplication.translate("addRectangleDialog", "Label", None, QtGui.QApplication.UnicodeUTF8))

