# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\advancedsimulationsetup.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_advancedSimulationSetupDialog(object):
    def setupUi(self, advancedSimulationSetupDialog):
        advancedSimulationSetupDialog.setObjectName("advancedSimulationSetupDialog")
        advancedSimulationSetupDialog.resize(295, 295)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(advancedSimulationSetupDialog.sizePolicy().hasHeightForWidth())
        advancedSimulationSetupDialog.setSizePolicy(sizePolicy)
        advancedSimulationSetupDialog.setMinimumSize(QtCore.QSize(295, 0))
        advancedSimulationSetupDialog.setMaximumSize(QtCore.QSize(265, 295))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/simModel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        advancedSimulationSetupDialog.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(advancedSimulationSetupDialog)
        self.buttonBox.setGeometry(QtCore.QRect(60, 260, 191, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(advancedSimulationSetupDialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 241, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 221, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pointPerCycleLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.pointPerCycleLabel.setObjectName("pointPerCycleLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pointPerCycleLabel)
        self.pointPerCycleSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.pointPerCycleSpinBox.setMinimumSize(QtCore.QSize(53, 0))
        self.pointPerCycleSpinBox.setMinimum(5)
        self.pointPerCycleSpinBox.setMaximum(60)
        self.pointPerCycleSpinBox.setSingleStep(1)
        self.pointPerCycleSpinBox.setProperty("value", 10)
        self.pointPerCycleSpinBox.setObjectName("pointPerCycleSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pointPerCycleSpinBox)
        self.timeScaleLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.timeScaleLabel.setObjectName("timeScaleLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.timeScaleLabel)
        self.timeScaleDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.timeScaleDoubleSpinBox.setMaximum(1.0)
        self.timeScaleDoubleSpinBox.setSingleStep(0.1)
        self.timeScaleDoubleSpinBox.setProperty("value", 1.0)
        self.timeScaleDoubleSpinBox.setObjectName("timeScaleDoubleSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.timeScaleDoubleSpinBox)
        self.previewSimulationSetupPushButton = QtWidgets.QPushButton(advancedSimulationSetupDialog)
        self.previewSimulationSetupPushButton.setGeometry(QtCore.QRect(10, 100, 235, 41))
        self.previewSimulationSetupPushButton.setMinimumSize(QtCore.QSize(0, 41))
        self.previewSimulationSetupPushButton.setMaximumSize(QtCore.QSize(16777215, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/previewImage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previewSimulationSetupPushButton.setIcon(icon1)
        self.previewSimulationSetupPushButton.setIconSize(QtCore.QSize(24, 24))
        self.previewSimulationSetupPushButton.setObjectName("previewSimulationSetupPushButton")
        self.previewFrame = QtWidgets.QFrame(advancedSimulationSetupDialog)
        self.previewFrame.setGeometry(QtCore.QRect(10, 140, 241, 111))
        self.previewFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.previewFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.previewFrame.setObjectName("previewFrame")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.previewFrame)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 221, 61))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.deltaFormLayout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.deltaFormLayout.setContentsMargins(0, 0, 0, 0)
        self.deltaFormLayout.setObjectName("deltaFormLayout")
        self.dxLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.dxLabel.setObjectName("dxLabel")
        self.deltaFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dxLabel)
        self.dxLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.dxLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.dxLineEdit.setObjectName("dxLineEdit")
        self.deltaFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dxLineEdit)
        self.dtLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.dtLabel.setObjectName("dtLabel")
        self.deltaFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dtLabel)
        self.dtLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.dtLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.dtLineEdit.setObjectName("dtLineEdit")
        self.deltaFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dtLineEdit)
        self.gridLayoutWidget = QtWidgets.QWidget(self.previewFrame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 60, 221, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.modelSizeGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.modelSizeGridLayout.setContentsMargins(0, 0, 0, 0)
        self.modelSizeGridLayout.setObjectName("modelSizeGridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.modelSizeGridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.modelSizeGridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.numericalSizeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.numericalSizeLabel.setObjectName("numericalSizeLabel")
        self.modelSizeGridLayout.addWidget(self.numericalSizeLabel, 1, 1, 1, 1)
        self.geometricSizeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.geometricSizeLabel.setObjectName("geometricSizeLabel")
        self.modelSizeGridLayout.addWidget(self.geometricSizeLabel, 0, 1, 1, 1)

        self.retranslateUi(advancedSimulationSetupDialog)
        self.buttonBox.accepted.connect(advancedSimulationSetupDialog.accept)
        self.buttonBox.rejected.connect(advancedSimulationSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(advancedSimulationSetupDialog)

    def retranslateUi(self, advancedSimulationSetupDialog):
        _translate = QtCore.QCoreApplication.translate
        advancedSimulationSetupDialog.setWindowTitle(_translate("advancedSimulationSetupDialog", "Advanced Simulation Setup"))
        self.pointPerCycleLabel.setText(_translate("advancedSimulationSetupDialog", "Point Per Cycle"))
        self.timeScaleLabel.setText(_translate("advancedSimulationSetupDialog", "Time Scale"))
        self.previewSimulationSetupPushButton.setText(_translate("advancedSimulationSetupDialog", "Preview Simulation Setup"))
        self.dxLabel.setText(_translate("advancedSimulationSetupDialog", "dx (mm)"))
        self.dtLabel.setText(_translate("advancedSimulationSetupDialog", "dt"))
        self.label.setText(_translate("advancedSimulationSetupDialog", "Geometric Model M x N:"))
        self.label_3.setText(_translate("advancedSimulationSetupDialog", "Numerical Model M x N:"))
        self.numericalSizeLabel.setText(_translate("advancedSimulationSetupDialog", "MxN"))
        self.geometricSizeLabel.setText(_translate("advancedSimulationSetupDialog", "MxN"))

import SimNDT.gui.resources_rc

