# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\boundarysetup.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_boundarySetupDialog(object):
    def setupUi(self, boundarySetupDialog):
        boundarySetupDialog.setObjectName("boundarySetupDialog")
        boundarySetupDialog.resize(270, 410)
        boundarySetupDialog.setMinimumSize(QtCore.QSize(270, 410))
        boundarySetupDialog.setMaximumSize(QtCore.QSize(270, 410))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/boundary.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        boundarySetupDialog.setWindowIcon(icon)
        boundarySetupDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox = QtWidgets.QDialogButtonBox(boundarySetupDialog)
        self.buttonBox.setGeometry(QtCore.QRect(70, 370, 191, 32))
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(boundarySetupDialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 251, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 231, 63))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.topSideLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.topSideLabel.setObjectName("topSideLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.topSideLabel)
        self.topComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.topComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.topComboBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.topComboBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.topComboBox.setObjectName("topComboBox")
        self.topComboBox.addItem("")
        self.topComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.topComboBox)
        self.topLayerSizeLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.topLayerSizeLabel.setObjectName("topLayerSizeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.topLayerSizeLabel)
        self.topLayerSizeLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.topLayerSizeLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.topLayerSizeLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.topLayerSizeLineEdit.setObjectName("topLayerSizeLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.topLayerSizeLineEdit)
        self.frame_2 = QtWidgets.QFrame(boundarySetupDialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 100, 251, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 231, 63))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.topSideLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.topSideLabel_2.setObjectName("topSideLabel_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.topSideLabel_2)
        self.bottomComboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.bottomComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.bottomComboBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.bottomComboBox.setObjectName("bottomComboBox")
        self.bottomComboBox.addItem("")
        self.bottomComboBox.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bottomComboBox)
        self.bottomLayerSizeLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.bottomLayerSizeLabel.setObjectName("bottomLayerSizeLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bottomLayerSizeLabel)
        self.bottomLayerSizeLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.bottomLayerSizeLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.bottomLayerSizeLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.bottomLayerSizeLineEdit.setObjectName("bottomLayerSizeLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bottomLayerSizeLineEdit)
        self.frame_3 = QtWidgets.QFrame(boundarySetupDialog)
        self.frame_3.setGeometry(QtCore.QRect(10, 190, 251, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.frame_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 231, 63))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.topSideLabel_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.topSideLabel_3.setObjectName("topSideLabel_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.topSideLabel_3)
        self.leftComboBox = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.leftComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.leftComboBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.leftComboBox.setObjectName("leftComboBox")
        self.leftComboBox.addItem("")
        self.leftComboBox.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leftComboBox)
        self.leftLayerSizeLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.leftLayerSizeLabel.setObjectName("leftLayerSizeLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.leftLayerSizeLabel)
        self.leftLayerSizeLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.leftLayerSizeLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.leftLayerSizeLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leftLayerSizeLineEdit.setObjectName("leftLayerSizeLineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.leftLayerSizeLineEdit)
        self.frame_4 = QtWidgets.QFrame(boundarySetupDialog)
        self.frame_4.setGeometry(QtCore.QRect(10, 280, 251, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.frame_4)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 231, 63))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.topSideLabel_4 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.topSideLabel_4.setObjectName("topSideLabel_4")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.topSideLabel_4)
        self.rightComboBox = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.rightComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.rightComboBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.rightComboBox.setObjectName("rightComboBox")
        self.rightComboBox.addItem("")
        self.rightComboBox.addItem("")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rightComboBox)
        self.rightLayerSizeLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.rightLayerSizeLabel.setObjectName("rightLayerSizeLabel")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.rightLayerSizeLabel)
        self.rightLayerSizeLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.rightLayerSizeLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.rightLayerSizeLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.rightLayerSizeLineEdit.setObjectName("rightLayerSizeLineEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rightLayerSizeLineEdit)

        self.retranslateUi(boundarySetupDialog)
        self.buttonBox.accepted.connect(boundarySetupDialog.accept)
        self.buttonBox.rejected.connect(boundarySetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(boundarySetupDialog)

    def retranslateUi(self, boundarySetupDialog):
        _translate = QtCore.QCoreApplication.translate
        boundarySetupDialog.setWindowTitle(_translate("boundarySetupDialog", "Boundary Conditions Setup"))
        self.topSideLabel.setText(_translate("boundarySetupDialog", "Top Side"))
        self.topComboBox.setItemText(0, _translate("boundarySetupDialog", "Absorbing Layer"))
        self.topComboBox.setItemText(1, _translate("boundarySetupDialog", "Air Boundary"))
        self.topLayerSizeLabel.setText(_translate("boundarySetupDialog", "Layer Size (mm)"))
        self.topLayerSizeLineEdit.setText(_translate("boundarySetupDialog", "0"))
        self.topSideLabel_2.setText(_translate("boundarySetupDialog", "Bottom Side"))
        self.bottomComboBox.setItemText(0, _translate("boundarySetupDialog", "Absorbing Layer"))
        self.bottomComboBox.setItemText(1, _translate("boundarySetupDialog", "Air Boundary"))
        self.bottomLayerSizeLabel.setText(_translate("boundarySetupDialog", "Layer Size (mm)"))
        self.bottomLayerSizeLineEdit.setText(_translate("boundarySetupDialog", "0"))
        self.topSideLabel_3.setText(_translate("boundarySetupDialog", "Left Side"))
        self.leftComboBox.setItemText(0, _translate("boundarySetupDialog", "Absorbing Layer"))
        self.leftComboBox.setItemText(1, _translate("boundarySetupDialog", "Air Boundary"))
        self.leftLayerSizeLabel.setText(_translate("boundarySetupDialog", "Layer Size (mm)"))
        self.leftLayerSizeLineEdit.setText(_translate("boundarySetupDialog", "0"))
        self.topSideLabel_4.setText(_translate("boundarySetupDialog", "Right Side"))
        self.rightComboBox.setItemText(0, _translate("boundarySetupDialog", "Absorbing Layer"))
        self.rightComboBox.setItemText(1, _translate("boundarySetupDialog", "Air Boundary"))
        self.rightLayerSizeLabel.setText(_translate("boundarySetupDialog", "Layer Size (mm)"))
        self.rightLayerSizeLineEdit.setText(_translate("boundarySetupDialog", "0"))

import SimNDT.gui.resources_rc

