# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boundarysetup.ui'
#
# Created: Tue Jun  3 20:27:32 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_boundarySetupDialog(object):
    def setupUi(self, boundarySetupDialog):
        boundarySetupDialog.setObjectName("boundarySetupDialog")
        boundarySetupDialog.resize(270, 410)
        boundarySetupDialog.setMinimumSize(QtCore.QSize(270, 410))
        boundarySetupDialog.setMaximumSize(QtCore.QSize(270, 410))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/boundary.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        boundarySetupDialog.setWindowIcon(icon)
        boundarySetupDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox = QtGui.QDialogButtonBox(boundarySetupDialog)
        self.buttonBox.setGeometry(QtCore.QRect(70, 370, 191, 32))
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtGui.QFrame(boundarySetupDialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 251, 80))
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.formLayoutWidget = QtGui.QWidget(self.frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 231, 63))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.topSideLabel = QtGui.QLabel(self.formLayoutWidget)
        self.topSideLabel.setObjectName("topSideLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.topSideLabel)
        self.topComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.topComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.topComboBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.topComboBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.topComboBox.setObjectName("topComboBox")
        self.topComboBox.addItem("")
        self.topComboBox.addItem("")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.topComboBox)
        self.topLayerSizeLabel = QtGui.QLabel(self.formLayoutWidget)
        self.topLayerSizeLabel.setObjectName("topLayerSizeLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.topLayerSizeLabel)
        self.topLayerSizeLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.topLayerSizeLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.topLayerSizeLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.topLayerSizeLineEdit.setObjectName("topLayerSizeLineEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.topLayerSizeLineEdit)
        self.frame_2 = QtGui.QFrame(boundarySetupDialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 100, 251, 80))
        self.frame_2.setFrameShape(QtGui.QFrame.Panel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.formLayoutWidget_2 = QtGui.QWidget(self.frame_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 231, 63))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.topSideLabel_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.topSideLabel_2.setObjectName("topSideLabel_2")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.topSideLabel_2)
        self.bottomComboBox = QtGui.QComboBox(self.formLayoutWidget_2)
        self.bottomComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.bottomComboBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.bottomComboBox.setObjectName("bottomComboBox")
        self.bottomComboBox.addItem("")
        self.bottomComboBox.addItem("")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.bottomComboBox)
        self.bottomLayerSizeLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.bottomLayerSizeLabel.setObjectName("bottomLayerSizeLabel")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.bottomLayerSizeLabel)
        self.bottomLayerSizeLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.bottomLayerSizeLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.bottomLayerSizeLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.bottomLayerSizeLineEdit.setObjectName("bottomLayerSizeLineEdit")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.bottomLayerSizeLineEdit)
        self.frame_3 = QtGui.QFrame(boundarySetupDialog)
        self.frame_3.setGeometry(QtCore.QRect(10, 190, 251, 80))
        self.frame_3.setFrameShape(QtGui.QFrame.Panel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.formLayoutWidget_3 = QtGui.QWidget(self.frame_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 231, 63))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.topSideLabel_3 = QtGui.QLabel(self.formLayoutWidget_3)
        self.topSideLabel_3.setObjectName("topSideLabel_3")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.topSideLabel_3)
        self.leftComboBox = QtGui.QComboBox(self.formLayoutWidget_3)
        self.leftComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.leftComboBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.leftComboBox.setObjectName("leftComboBox")
        self.leftComboBox.addItem("")
        self.leftComboBox.addItem("")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.leftComboBox)
        self.leftLayerSizeLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.leftLayerSizeLabel.setObjectName("leftLayerSizeLabel")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.leftLayerSizeLabel)
        self.leftLayerSizeLineEdit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.leftLayerSizeLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.leftLayerSizeLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leftLayerSizeLineEdit.setObjectName("leftLayerSizeLineEdit")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.leftLayerSizeLineEdit)
        self.frame_4 = QtGui.QFrame(boundarySetupDialog)
        self.frame_4.setGeometry(QtCore.QRect(10, 280, 251, 80))
        self.frame_4.setFrameShape(QtGui.QFrame.Panel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.formLayoutWidget_4 = QtGui.QWidget(self.frame_4)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 231, 63))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.topSideLabel_4 = QtGui.QLabel(self.formLayoutWidget_4)
        self.topSideLabel_4.setObjectName("topSideLabel_4")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.topSideLabel_4)
        self.rightComboBox = QtGui.QComboBox(self.formLayoutWidget_4)
        self.rightComboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.rightComboBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.rightComboBox.setObjectName("rightComboBox")
        self.rightComboBox.addItem("")
        self.rightComboBox.addItem("")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.rightComboBox)
        self.rightLayerSizeLabel = QtGui.QLabel(self.formLayoutWidget_4)
        self.rightLayerSizeLabel.setObjectName("rightLayerSizeLabel")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.rightLayerSizeLabel)
        self.rightLayerSizeLineEdit = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.rightLayerSizeLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.rightLayerSizeLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.rightLayerSizeLineEdit.setObjectName("rightLayerSizeLineEdit")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.rightLayerSizeLineEdit)

        self.retranslateUi(boundarySetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), boundarySetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), boundarySetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(boundarySetupDialog)

    def retranslateUi(self, boundarySetupDialog):
        boundarySetupDialog.setWindowTitle(QtGui.QApplication.translate("boundarySetupDialog", "Boundary Conditions Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.topSideLabel.setText(QtGui.QApplication.translate("boundarySetupDialog", "Top Side", None, QtGui.QApplication.UnicodeUTF8))
        self.topComboBox.setItemText(0, QtGui.QApplication.translate("boundarySetupDialog", "Absorbing Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.topComboBox.setItemText(1, QtGui.QApplication.translate("boundarySetupDialog", "Air Boundary", None, QtGui.QApplication.UnicodeUTF8))
        self.topLayerSizeLabel.setText(QtGui.QApplication.translate("boundarySetupDialog", "Layer Size (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.topLayerSizeLineEdit.setText(QtGui.QApplication.translate("boundarySetupDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.topSideLabel_2.setText(QtGui.QApplication.translate("boundarySetupDialog", "Bottom Side", None, QtGui.QApplication.UnicodeUTF8))
        self.bottomComboBox.setItemText(0, QtGui.QApplication.translate("boundarySetupDialog", "Absorbing Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.bottomComboBox.setItemText(1, QtGui.QApplication.translate("boundarySetupDialog", "Air Boundary", None, QtGui.QApplication.UnicodeUTF8))
        self.bottomLayerSizeLabel.setText(QtGui.QApplication.translate("boundarySetupDialog", "Layer Size (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.bottomLayerSizeLineEdit.setText(QtGui.QApplication.translate("boundarySetupDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.topSideLabel_3.setText(QtGui.QApplication.translate("boundarySetupDialog", "Left Side", None, QtGui.QApplication.UnicodeUTF8))
        self.leftComboBox.setItemText(0, QtGui.QApplication.translate("boundarySetupDialog", "Absorbing Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.leftComboBox.setItemText(1, QtGui.QApplication.translate("boundarySetupDialog", "Air Boundary", None, QtGui.QApplication.UnicodeUTF8))
        self.leftLayerSizeLabel.setText(QtGui.QApplication.translate("boundarySetupDialog", "Layer Size (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.leftLayerSizeLineEdit.setText(QtGui.QApplication.translate("boundarySetupDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.topSideLabel_4.setText(QtGui.QApplication.translate("boundarySetupDialog", "Right Side", None, QtGui.QApplication.UnicodeUTF8))
        self.rightComboBox.setItemText(0, QtGui.QApplication.translate("boundarySetupDialog", "Absorbing Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.rightComboBox.setItemText(1, QtGui.QApplication.translate("boundarySetupDialog", "Air Boundary", None, QtGui.QApplication.UnicodeUTF8))
        self.rightLayerSizeLabel.setText(QtGui.QApplication.translate("boundarySetupDialog", "Layer Size (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.rightLayerSizeLineEdit.setText(QtGui.QApplication.translate("boundarySetupDialog", "0", None, QtGui.QApplication.UnicodeUTF8))