# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\linearscansetup.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_linearScanSetupDialog(object):
    def setupUi(self, linearScanSetupDialog):
        linearScanSetupDialog.setObjectName("linearScanSetupDialog")
        linearScanSetupDialog.resize(300, 500)
        linearScanSetupDialog.setMinimumSize(QtCore.QSize(300, 500))
        linearScanSetupDialog.setMaximumSize(QtCore.QSize(300, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/linearScan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        linearScanSetupDialog.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(linearScanSetupDialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 460, 230, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(linearScanSetupDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 271, 80))
        self.groupBox.setObjectName("groupBox")
        self.transmissionRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.transmissionRadioButton.setGeometry(QtCore.QRect(20, 30, 161, 18))
        self.transmissionRadioButton.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.transmissionRadioButton.setObjectName("transmissionRadioButton")
        self.pulseEchoRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.pulseEchoRadioButton.setGeometry(QtCore.QRect(20, 50, 97, 18))
        self.pulseEchoRadioButton.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.pulseEchoRadioButton.setObjectName("pulseEchoRadioButton")
        self.groupBox_2 = QtWidgets.QGroupBox(linearScanSetupDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 100, 272, 350))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName("formLayout")
        self.transducerLocationLabel = QtWidgets.QLabel(self.groupBox_2)
        self.transducerLocationLabel.setObjectName("transducerLocationLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.transducerLocationLabel)
        self.locationComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.locationComboBox.setMinimumSize(QtCore.QSize(80, 0))
        self.locationComboBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.locationComboBox.setObjectName("locationComboBox")
        self.locationComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.locationComboBox)
        self.pointSourceCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.pointSourceCheckBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.pointSourceCheckBox.setToolTip("")
        self.pointSourceCheckBox.setObjectName("pointSourceCheckBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pointSourceCheckBox)
        self.transducerSizeLabel = QtWidgets.QLabel(self.groupBox_2)
        self.transducerSizeLabel.setObjectName("transducerSizeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.transducerSizeLabel)
        self.transducerSizeLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.transducerSizeLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.transducerSizeLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.transducerSizeLineEdit.setObjectName("transducerSizeLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.transducerSizeLineEdit)
        self.borderOffsetLabel = QtWidgets.QLabel(self.groupBox_2)
        self.borderOffsetLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.borderOffsetLabel.setObjectName("borderOffsetLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.borderOffsetLabel)
        self.borderOffsetLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.borderOffsetLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.borderOffsetLineEdit.setObjectName("borderOffsetLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.borderOffsetLineEdit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.startOffsetLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.startOffsetLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        self.startOffsetLineEdit.setFont(font)
        self.startOffsetLineEdit.setText("")
        self.startOffsetLineEdit.setObjectName("startOffsetLineEdit")
        self.horizontalLayout.addWidget(self.startOffsetLineEdit)
        self.stopOffsetLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.stopOffsetLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        self.stopOffsetLineEdit.setFont(font)
        self.stopOffsetLineEdit.setObjectName("stopOffsetLineEdit")
        self.horizontalLayout.addWidget(self.stopOffsetLineEdit)
        self.stepOffsetLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.stepOffsetLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        self.stepOffsetLineEdit.setFont(font)
        self.stepOffsetLineEdit.setObjectName("stepOffsetLineEdit")
        self.horizontalLayout.addWidget(self.stepOffsetLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.previewPushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.previewPushButton.setMinimumSize(QtCore.QSize(0, 41))
        self.previewPushButton.setMaximumSize(QtCore.QSize(1666666, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/previewImage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previewPushButton.setIcon(icon1)
        self.previewPushButton.setIconSize(QtCore.QSize(24, 24))
        self.previewPushButton.setObjectName("previewPushButton")
        self.verticalLayout.addWidget(self.previewPushButton)
        self.advancedParametersSetupPushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.advancedParametersSetupPushButton.setMinimumSize(QtCore.QSize(0, 41))
        self.advancedParametersSetupPushButton.setMaximumSize(QtCore.QSize(1666666, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/simModel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.advancedParametersSetupPushButton.setIcon(icon2)
        self.advancedParametersSetupPushButton.setIconSize(QtCore.QSize(24, 24))
        self.advancedParametersSetupPushButton.setObjectName("advancedParametersSetupPushButton")
        self.verticalLayout.addWidget(self.advancedParametersSetupPushButton)
        self.signalSetupPushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.signalSetupPushButton.setMinimumSize(QtCore.QSize(0, 41))
        self.signalSetupPushButton.setMaximumSize(QtCore.QSize(1666666, 41))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/signal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signalSetupPushButton.setIcon(icon3)
        self.signalSetupPushButton.setIconSize(QtCore.QSize(24, 24))
        self.signalSetupPushButton.setCheckable(False)
        self.signalSetupPushButton.setDefault(False)
        self.signalSetupPushButton.setFlat(False)
        self.signalSetupPushButton.setObjectName("signalSetupPushButton")
        self.verticalLayout.addWidget(self.signalSetupPushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(linearScanSetupDialog)
        self.buttonBox.accepted.connect(linearScanSetupDialog.accept)
        self.buttonBox.rejected.connect(linearScanSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(linearScanSetupDialog)

    def retranslateUi(self, linearScanSetupDialog):
        _translate = QtCore.QCoreApplication.translate
        linearScanSetupDialog.setWindowTitle(_translate("linearScanSetupDialog", "Linear Scan Setup"))
        self.groupBox.setTitle(_translate("linearScanSetupDialog", "Inspection Method"))
        self.transmissionRadioButton.setText(_translate("linearScanSetupDialog", "Through Transmission"))
        self.pulseEchoRadioButton.setText(_translate("linearScanSetupDialog", "Pulse Echo"))
        self.groupBox_2.setTitle(_translate("linearScanSetupDialog", "Transducer Setup"))
        self.transducerLocationLabel.setText(_translate("linearScanSetupDialog", "Transducer Location"))
        self.locationComboBox.setItemText(0, _translate("linearScanSetupDialog", "Top"))
        self.pointSourceCheckBox.setText(_translate("linearScanSetupDialog", "Point Source"))
        self.transducerSizeLabel.setText(_translate("linearScanSetupDialog", "Transducer Size (mm)"))
        self.borderOffsetLabel.setToolTip(_translate("linearScanSetupDialog", "<html><head/><body><p align=\"justify\"><span style=\" font-size:14pt;\">Border Offset is measured taking into account the top border as origin. Only positive values are allowed that indicates offsets towards below.</span><br/><img src=\":/helperBorderOffset.png\"/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p></body></html>"))
        self.borderOffsetLabel.setText(_translate("linearScanSetupDialog", "Border Offset (mm)"))
        self.borderOffsetLineEdit.setToolTip(_translate("linearScanSetupDialog", "<html><head/><body><p align=\"justify\"><span style=\" font-size:14pt;\">Border Offset is measured taking into account the top border as origin. Only positive values are allowed that indicates offsets towards below.</span><br/><img src=\":/helperBorderOffset.png\"/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p></body></html>"))
        self.label.setToolTip(_translate("linearScanSetupDialog", "<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt;\">Offset Range is measured taking into account the origin as the center of the scenario.</span></p><p align=\"justify\"><span style=\" font-size:16pt;\">Negative values indicate offsets towards the left side while positive values indicate offsets towards the right side.</span></p><p><img src=\":/helpLinearScan.png\"/><br/></p><p><br/></p><p><br/></p></body></html>"))
        self.label.setText(_translate("linearScanSetupDialog", " Offset Range (mm):"))
        self.label_2.setToolTip(_translate("linearScanSetupDialog", "<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt;\">Offset Range is measured taking into account the origin as the center of the scenario.</span></p><p align=\"justify\"><span style=\" font-size:16pt;\">Negative values indicate offsets towards the left side while positive values indicate offsets towards the right side.</span></p><p><br/></p><p><img src=\":/helpLinearScan.png\"/></p><p><br/></p><p><br/></p></body></html>"))
        self.label_2.setText(_translate("linearScanSetupDialog", "(Start,"))
        self.label_3.setToolTip(_translate("linearScanSetupDialog", "<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt;\">Offset Range is measured taking into account the origin as the center of the scenario.</span></p><p align=\"justify\"><span style=\" font-size:16pt;\">Negative values indicate offsets towards the left side while positive values indicate offsets towards the right side.</span></p><p><br/></p><p><img src=\":/helpLinearScan.png\"/></p><p><br/></p><p><br/></p></body></html>"))
        self.label_3.setText(_translate("linearScanSetupDialog", "Stop,"))
        self.label_4.setToolTip(_translate("linearScanSetupDialog", "<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt;\">Offset Range is measured taking into account the origin as the center of the scenario.</span></p><p align=\"justify\"><span style=\" font-size:16pt;\">Negative values indicate offsets towards the left side while positive values indicate offsets towards the right side.</span></p><p><br/></p><p><img src=\":/helpLinearScan.png\"/></p><p><br/></p><p><br/></p></body></html>"))
        self.label_4.setText(_translate("linearScanSetupDialog", "Step)"))
        self.startOffsetLineEdit.setToolTip(_translate("linearScanSetupDialog", "<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt;\">Offset Range is measured taking into account the origin as the center of the scenario.</span></p><p align=\"justify\"><span style=\" font-size:16pt;\">Negative values indicate offsets towards the left side while positive values indicate offsets towards the right side.</span></p><p><br/></p><p><img src=\":/helpLinearScan.png\"/></p><p><br/></p><p><br/></p></body></html>"))
        self.stopOffsetLineEdit.setToolTip(_translate("linearScanSetupDialog", "<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt;\">Offset Range is measured taking into account the origin as the center of the scenario.</span></p><p align=\"justify\"><span style=\" font-size:16pt;\">Negative values indicate offsets towards the left side while positive values indicate offsets towards the right side.</span></p><p><br/></p><p><img src=\":/helpLinearScan.png\"/></p><p><br/></p><p><br/></p></body></html>"))
        self.stepOffsetLineEdit.setToolTip(_translate("linearScanSetupDialog", "<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt;\">Offset Range is measured taking into account the origin as the center of the scenario.</span></p><p align=\"justify\"><span style=\" font-size:16pt;\">Negative values indicate offsets towards the left side while positive values indicate offsets towards the right side.</span></p><p><br/></p><p><img src=\":/helpLinearScan.png\"/></p><p><br/></p><p><br/></p></body></html>"))
        self.previewPushButton.setText(_translate("linearScanSetupDialog", "Preview Transducer Setup"))
        self.advancedParametersSetupPushButton.setText(_translate("linearScanSetupDialog", "Advanced Parameters Setup"))
        self.signalSetupPushButton.setText(_translate("linearScanSetupDialog", "Signal Parameters"))

import SimNDT.gui.resources_rc

