# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\loadimagemainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoadImageMainWindow(object):
    def setupUi(self, LoadImageMainWindow):
        LoadImageMainWindow.setObjectName("LoadImageMainWindow")
        LoadImageMainWindow.setWindowModality(QtCore.Qt.WindowModal)
        LoadImageMainWindow.resize(724, 600)
        LoadImageMainWindow.setMinimumSize(QtCore.QSize(0, 0))
        LoadImageMainWindow.setMaximumSize(QtCore.QSize(3000, 3000))
        LoadImageMainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        LoadImageMainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        LoadImageMainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        LoadImageMainWindow.setDocumentMode(False)
        LoadImageMainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(LoadImageMainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(724, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vBox = QtWidgets.QVBoxLayout()
        self.vBox.setObjectName("vBox")
        self.imageFrame = QtWidgets.QFrame(self.centralwidget)
        self.imageFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.imageFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.imageFrame.setObjectName("imageFrame")
        self.vBox.addWidget(self.imageFrame)
        self.verticalLayout.addLayout(self.vBox)
        self.hBox = QtWidgets.QHBoxLayout()
        self.hBox.setObjectName("hBox")
        self.numberLabelsLabel = QtWidgets.QLabel(self.centralwidget)
        self.numberLabelsLabel.setObjectName("numberLabelsLabel")
        self.hBox.addWidget(self.numberLabelsLabel)
        self.numberLabelsSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.numberLabelsSpinBox.setMinimum(1)
        self.numberLabelsSpinBox.setMaximum(7)
        self.numberLabelsSpinBox.setObjectName("numberLabelsSpinBox")
        self.hBox.addWidget(self.numberLabelsSpinBox)
        self.PixelLabel = QtWidgets.QLabel(self.centralwidget)
        self.PixelLabel.setObjectName("PixelLabel")
        self.hBox.addWidget(self.PixelLabel)
        self.PixelLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PixelLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.PixelLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.PixelLineEdit.setObjectName("PixelLineEdit")
        self.hBox.addWidget(self.PixelLineEdit)
        self.getLabeledImagePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.getLabeledImagePushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.getLabeledImagePushButton.setObjectName("getLabeledImagePushButton")
        self.hBox.addWidget(self.getLabeledImagePushButton)
        self.verticalLayout.addLayout(self.hBox)
        LoadImageMainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(LoadImageMainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        LoadImageMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionRotate_90_Counter_Clockwise = QtWidgets.QAction(LoadImageMainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rotate90A.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRotate_90_Counter_Clockwise.setIcon(icon)
        self.actionRotate_90_Counter_Clockwise.setObjectName("actionRotate_90_Counter_Clockwise")
        self.actionRotate_90_Clockwise = QtWidgets.QAction(LoadImageMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/rotate90H.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRotate_90_Clockwise.setIcon(icon1)
        self.actionRotate_90_Clockwise.setObjectName("actionRotate_90_Clockwise")
        self.actionFlip_Horizontal = QtWidgets.QAction(LoadImageMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/flipH.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFlip_Horizontal.setIcon(icon2)
        self.actionFlip_Horizontal.setObjectName("actionFlip_Horizontal")
        self.actionFlip_Vertical = QtWidgets.QAction(LoadImageMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/flipV.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFlip_Vertical.setIcon(icon3)
        self.actionFlip_Vertical.setObjectName("actionFlip_Vertical")
        self.actionShow_Original_Image = QtWidgets.QAction(LoadImageMainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_Original_Image.setIcon(icon4)
        self.actionShow_Original_Image.setObjectName("actionShow_Original_Image")
        self.actionOpen_Image = QtWidgets.QAction(LoadImageMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Image.setIcon(icon5)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.toolBar.addAction(self.actionOpen_Image)
        self.toolBar.addAction(self.actionShow_Original_Image)
        self.toolBar.addAction(self.actionRotate_90_Counter_Clockwise)
        self.toolBar.addAction(self.actionRotate_90_Clockwise)
        self.toolBar.addAction(self.actionFlip_Horizontal)
        self.toolBar.addAction(self.actionFlip_Vertical)
        self.toolBar.addSeparator()

        self.retranslateUi(LoadImageMainWindow)
        QtCore.QMetaObject.connectSlotsByName(LoadImageMainWindow)

    def retranslateUi(self, LoadImageMainWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadImageMainWindow.setWindowTitle(_translate("LoadImageMainWindow", "MainWindow"))
        self.numberLabelsLabel.setText(_translate("LoadImageMainWindow", "# Number of Labels"))
        self.PixelLabel.setText(_translate("LoadImageMainWindow", "Pixel/mm"))
        self.getLabeledImagePushButton.setText(_translate("LoadImageMainWindow", "Get Labeled Image"))
        self.toolBar.setWindowTitle(_translate("LoadImageMainWindow", "toolBar"))
        self.actionRotate_90_Counter_Clockwise.setText(_translate("LoadImageMainWindow", "Rotate 90º Counter Clockwise"))
        self.actionRotate_90_Counter_Clockwise.setToolTip(_translate("LoadImageMainWindow", "Rotate 90º clockwise"))
        self.actionRotate_90_Clockwise.setText(_translate("LoadImageMainWindow", "Rotate 90º Clockwise"))
        self.actionFlip_Horizontal.setText(_translate("LoadImageMainWindow", "Flip Horizontal"))
        self.actionFlip_Horizontal.setToolTip(_translate("LoadImageMainWindow", "Flip Horizontal"))
        self.actionFlip_Vertical.setText(_translate("LoadImageMainWindow", "Flip Vertical"))
        self.actionFlip_Vertical.setToolTip(_translate("LoadImageMainWindow", "Flip Vertical"))
        self.actionShow_Original_Image.setText(_translate("LoadImageMainWindow", "Show Original Image"))
        self.actionShow_Original_Image.setToolTip(_translate("LoadImageMainWindow", "Show Original Image"))
        self.actionOpen_Image.setText(_translate("LoadImageMainWindow", "Open Image"))
        self.actionOpen_Image.setToolTip(_translate("LoadImageMainWindow", "Open Image"))

import SimNDT.gui.resources_rc

