# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\runsimulation.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_runSimulationDialog(object):
    def setupUi(self, runSimulationDialog):
        runSimulationDialog.setObjectName("runSimulationDialog")
        runSimulationDialog.resize(275, 340)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(runSimulationDialog.sizePolicy().hasHeightForWidth())
        runSimulationDialog.setSizePolicy(sizePolicy)
        runSimulationDialog.setMinimumSize(QtCore.QSize(275, 340))
        runSimulationDialog.setMaximumSize(QtCore.QSize(275, 340))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/runGL.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        runSimulationDialog.setWindowIcon(icon)
        runSimulationDialog.setSizeGripEnabled(False)
        self.verticalLayoutWidget = QtWidgets.QWidget(runSimulationDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 251, 326))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.viewCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.viewCheckBox.setObjectName("viewCheckBox")
        self.verticalLayout.addWidget(self.viewCheckBox)
        self.receiverCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.receiverCheckBox.setObjectName("receiverCheckBox")
        self.verticalLayout.addWidget(self.receiverCheckBox)
        self.snapshotsPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.snapshotsPushButton.setMinimumSize(QtCore.QSize(0, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/snapshots.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.snapshotsPushButton.setIcon(icon1)
        self.snapshotsPushButton.setIconSize(QtCore.QSize(20, 20))
        self.snapshotsPushButton.setObjectName("snapshotsPushButton")
        self.verticalLayout.addWidget(self.snapshotsPushButton)
        self.stepsLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.stepsLabel.setObjectName("stepsLabel")
        self.verticalLayout.addWidget(self.stepsLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName("formLayout")
        self.snapshotStepLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.snapshotStepLabel.setObjectName("snapshotStepLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.snapshotStepLabel)
        self.snapshotStepSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.snapshotStepSpinBox.setMinimum(50)
        self.snapshotStepSpinBox.setMaximum(1000)
        self.snapshotStepSpinBox.setSingleStep(50)
        self.snapshotStepSpinBox.setProperty("value", 100)
        self.snapshotStepSpinBox.setObjectName("snapshotStepSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.snapshotStepSpinBox)
        self.visualizacionRangeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.visualizacionRangeLabel.setObjectName("visualizacionRangeLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.visualizacionRangeLabel)
        self.visualizacionRangeSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.visualizacionRangeSpinBox.setMinimum(10)
        self.visualizacionRangeSpinBox.setMaximum(80)
        self.visualizacionRangeSpinBox.setSingleStep(10)
        self.visualizacionRangeSpinBox.setProperty("value", 60)
        self.visualizacionRangeSpinBox.setObjectName("visualizacionRangeSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.visualizacionRangeSpinBox)
        self.enableSavingFieldsLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.enableSavingFieldsLabel.setObjectName("enableSavingFieldsLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.enableSavingFieldsLabel)
        self.enableSavingFieldsCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.enableSavingFieldsCheckBox.setObjectName("enableSavingFieldsCheckBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.enableSavingFieldsCheckBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.colormapLayout = QtWidgets.QHBoxLayout()
        self.colormapLayout.setObjectName("colormapLayout")
        self.colormapComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.colormapComboBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.colormapComboBox.setObjectName("colormapComboBox")
        self.colormapLayout.addWidget(self.colormapComboBox)
        self.verticalLayout.addLayout(self.colormapLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(runSimulationDialog)
        self.buttonBox.accepted.connect(runSimulationDialog.accept)
        self.buttonBox.rejected.connect(runSimulationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(runSimulationDialog)

    def retranslateUi(self, runSimulationDialog):
        _translate = QtCore.QCoreApplication.translate
        runSimulationDialog.setWindowTitle(_translate("runSimulationDialog", "Dialog"))
        self.viewCheckBox.setText(_translate("runSimulationDialog", "Enable View-Mode Simulation"))
        self.receiverCheckBox.setText(_translate("runSimulationDialog", "Enable View-Mode Receiver Signal"))
        self.snapshotsPushButton.setToolTip(_translate("runSimulationDialog", "Enable Snapshots"))
        self.snapshotsPushButton.setText(_translate("runSimulationDialog", "Enable Snapshots"))
        self.stepsLabel.setText(_translate("runSimulationDialog", "Simulation Time Steps:"))
        self.snapshotStepLabel.setText(_translate("runSimulationDialog", "Snapshot Step"))
        self.visualizacionRangeLabel.setText(_translate("runSimulationDialog", "VIsualizacion Range"))
        self.visualizacionRangeSpinBox.setSuffix(_translate("runSimulationDialog", "dB"))
        self.enableSavingFieldsLabel.setText(_translate("runSimulationDialog", "Enable Saving Vx, Vy Fields"))

import SimNDT.gui.resources_rc

