# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'runsimulation.ui'
#
# Created: Wed Oct 15 22:29:09 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_runSimulationDialog(object):
    def setupUi(self, runSimulationDialog):
        runSimulationDialog.setObjectName("runSimulationDialog")
        runSimulationDialog.resize(275, 340)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(runSimulationDialog.sizePolicy().hasHeightForWidth())
        runSimulationDialog.setSizePolicy(sizePolicy)
        runSimulationDialog.setMinimumSize(QtCore.QSize(275, 340))
        runSimulationDialog.setMaximumSize(QtCore.QSize(275, 340))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/runGL.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        runSimulationDialog.setWindowIcon(icon)
        runSimulationDialog.setSizeGripEnabled(False)
        self.verticalLayoutWidget = QtGui.QWidget(runSimulationDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 251, 326))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.viewCheckBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.viewCheckBox.setObjectName("viewCheckBox")
        self.verticalLayout.addWidget(self.viewCheckBox)
        self.receiverCheckBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.receiverCheckBox.setObjectName("receiverCheckBox")
        self.verticalLayout.addWidget(self.receiverCheckBox)
        self.snapshotsPushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.snapshotsPushButton.setMinimumSize(QtCore.QSize(0, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/snapshots.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.snapshotsPushButton.setIcon(icon1)
        self.snapshotsPushButton.setIconSize(QtCore.QSize(20, 20))
        self.snapshotsPushButton.setObjectName("snapshotsPushButton")
        self.verticalLayout.addWidget(self.snapshotsPushButton)
        self.stepsLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.stepsLabel.setObjectName("stepsLabel")
        self.verticalLayout.addWidget(self.stepsLabel)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName("formLayout")
        self.snapshotStepLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.snapshotStepLabel.setObjectName("snapshotStepLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.snapshotStepLabel)
        self.snapshotStepSpinBox = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.snapshotStepSpinBox.setMinimum(50)
        self.snapshotStepSpinBox.setMaximum(1000)
        self.snapshotStepSpinBox.setSingleStep(50)
        self.snapshotStepSpinBox.setProperty("value", 100)
        self.snapshotStepSpinBox.setObjectName("snapshotStepSpinBox")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.snapshotStepSpinBox)
        self.visualizacionRangeLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.visualizacionRangeLabel.setObjectName("visualizacionRangeLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.visualizacionRangeLabel)
        self.visualizacionRangeSpinBox = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.visualizacionRangeSpinBox.setMinimum(10)
        self.visualizacionRangeSpinBox.setMaximum(80)
        self.visualizacionRangeSpinBox.setSingleStep(10)
        self.visualizacionRangeSpinBox.setProperty("value", 60)
        self.visualizacionRangeSpinBox.setObjectName("visualizacionRangeSpinBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.visualizacionRangeSpinBox)
        self.enableSavingFieldsLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.enableSavingFieldsLabel.setObjectName("enableSavingFieldsLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.enableSavingFieldsLabel)
        self.enableSavingFieldsCheckBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.enableSavingFieldsCheckBox.setObjectName("enableSavingFieldsCheckBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.enableSavingFieldsCheckBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.colormapLayout = QtGui.QHBoxLayout()
        self.colormapLayout.setObjectName("colormapLayout")
        self.colormapComboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.colormapComboBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.colormapComboBox.setObjectName("colormapComboBox")
        self.colormapLayout.addWidget(self.colormapComboBox)
        self.verticalLayout.addLayout(self.colormapLayout)
        self.buttonBox = QtGui.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(runSimulationDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), runSimulationDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), runSimulationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(runSimulationDialog)

    def retranslateUi(self, runSimulationDialog):
        runSimulationDialog.setWindowTitle(QtGui.QApplication.translate("runSimulationDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.viewCheckBox.setText(QtGui.QApplication.translate("runSimulationDialog", "Enable View-Mode Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.receiverCheckBox.setText(QtGui.QApplication.translate("runSimulationDialog", "Enable View-Mode Receiver Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.snapshotsPushButton.setToolTip(QtGui.QApplication.translate("runSimulationDialog", "Enable Snapshots", None, QtGui.QApplication.UnicodeUTF8))
        self.snapshotsPushButton.setText(QtGui.QApplication.translate("runSimulationDialog", "Enable Snapshots", None, QtGui.QApplication.UnicodeUTF8))
        self.stepsLabel.setText(QtGui.QApplication.translate("runSimulationDialog", "Simulation Time Steps:", None, QtGui.QApplication.UnicodeUTF8))
        self.snapshotStepLabel.setText(QtGui.QApplication.translate("runSimulationDialog", "Snapshot Step", None, QtGui.QApplication.UnicodeUTF8))
        self.visualizacionRangeLabel.setText(QtGui.QApplication.translate("runSimulationDialog", "VIsualizacion Range", None, QtGui.QApplication.UnicodeUTF8))
        self.visualizacionRangeSpinBox.setSuffix(QtGui.QApplication.translate("runSimulationDialog", "dB", None, QtGui.QApplication.UnicodeUTF8))
        self.enableSavingFieldsLabel.setText(QtGui.QApplication.translate("runSimulationDialog", "Enable Saving Vx, Vy Fields", None, QtGui.QApplication.UnicodeUTF8))

