# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\twophasemodeldrycase.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_twoPhaseModelDryCaseDialog(object):
    def setupUi(self, twoPhaseModelDryCaseDialog):
        twoPhaseModelDryCaseDialog.setObjectName("twoPhaseModelDryCaseDialog")
        twoPhaseModelDryCaseDialog.resize(476, 271)
        twoPhaseModelDryCaseDialog.setMaximumSize(QtCore.QSize(476, 271))
        twoPhaseModelDryCaseDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox = QtWidgets.QDialogButtonBox(twoPhaseModelDryCaseDialog)
        self.buttonBox.setGeometry(QtCore.QRect(90, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(twoPhaseModelDryCaseDialog)
        self.frame.setGeometry(QtCore.QRect(20, 20, 441, 182))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 419, 162))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gradingDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.gradingDoubleSpinBox.setMinimum(0.01)
        self.gradingDoubleSpinBox.setMaximum(0.8)
        self.gradingDoubleSpinBox.setSingleStep(0.2)
        self.gradingDoubleSpinBox.setProperty("value", 0.1)
        self.gradingDoubleSpinBox.setObjectName("gradingDoubleSpinBox")
        self.gridLayout.addWidget(self.gradingDoubleSpinBox, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.labelSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.labelSpinBox.setMaximum(240)
        self.labelSpinBox.setSingleStep(40)
        self.labelSpinBox.setProperty("value", 40)
        self.labelSpinBox.setObjectName("labelSpinBox")
        self.gridLayout.addWidget(self.labelSpinBox, 1, 0, 1, 1)
        self.minAspectRatioDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.minAspectRatioDoubleSpinBox.setMinimum(0.2)
        self.minAspectRatioDoubleSpinBox.setMaximum(1.0)
        self.minAspectRatioDoubleSpinBox.setProperty("value", 0.5)
        self.minAspectRatioDoubleSpinBox.setObjectName("minAspectRatioDoubleSpinBox")
        self.gridLayout.addWidget(self.minAspectRatioDoubleSpinBox, 3, 2, 1, 1)
        self.minDiameterDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.minDiameterDoubleSpinBox.setMinimum(0.2)
        self.minDiameterDoubleSpinBox.setMaximum(20.0)
        self.minDiameterDoubleSpinBox.setSingleStep(0.1)
        self.minDiameterDoubleSpinBox.setProperty("value", 0.5)
        self.minDiameterDoubleSpinBox.setObjectName("minDiameterDoubleSpinBox")
        self.gridLayout.addWidget(self.minDiameterDoubleSpinBox, 0, 2, 1, 1)
        self.fractionLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.fractionLabel.setObjectName("fractionLabel")
        self.gridLayout.addWidget(self.fractionLabel, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.fractionDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.fractionDoubleSpinBox.setMinimum(0.1)
        self.fractionDoubleSpinBox.setMaximum(70.0)
        self.fractionDoubleSpinBox.setProperty("value", 10.0)
        self.fractionDoubleSpinBox.setObjectName("fractionDoubleSpinBox")
        self.gridLayout.addWidget(self.fractionDoubleSpinBox, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 3, 1, 1)
        self.maxDiameterDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.maxDiameterDoubleSpinBox.setMinimum(0.02)
        self.maxDiameterDoubleSpinBox.setMaximum(20.0)
        self.maxDiameterDoubleSpinBox.setSingleStep(0.1)
        self.maxDiameterDoubleSpinBox.setProperty("value", 10.0)
        self.maxDiameterDoubleSpinBox.setObjectName("maxDiameterDoubleSpinBox")
        self.gridLayout.addWidget(self.maxDiameterDoubleSpinBox, 1, 2, 1, 1)
        self.maxAspectRatioDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.maxAspectRatioDoubleSpinBox.setMinimum(0.3)
        self.maxAspectRatioDoubleSpinBox.setMaximum(1.0)
        self.maxAspectRatioDoubleSpinBox.setSingleStep(0.1)
        self.maxAspectRatioDoubleSpinBox.setProperty("value", 0.8)
        self.maxAspectRatioDoubleSpinBox.setObjectName("maxAspectRatioDoubleSpinBox")
        self.gridLayout.addWidget(self.maxAspectRatioDoubleSpinBox, 4, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 3, 1, 1)
        self.labelLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelLabel.setObjectName("labelLabel")
        self.gridLayout.addWidget(self.labelLabel, 1, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(twoPhaseModelDryCaseDialog)
        self.progressBar.setGeometry(QtCore.QRect(30, 210, 411, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(twoPhaseModelDryCaseDialog)
        self.buttonBox.accepted.connect(twoPhaseModelDryCaseDialog.accept)
        self.buttonBox.rejected.connect(twoPhaseModelDryCaseDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(twoPhaseModelDryCaseDialog)

    def retranslateUi(self, twoPhaseModelDryCaseDialog):
        _translate = QtCore.QCoreApplication.translate
        twoPhaseModelDryCaseDialog.setWindowTitle(_translate("twoPhaseModelDryCaseDialog", "Two-Phase Model (Dry Case)"))
        self.label_5.setText(_translate("twoPhaseModelDryCaseDialog", "Grading Curve Coeff"))
        self.label_4.setText(_translate("twoPhaseModelDryCaseDialog", "Max Diameter (mm)"))
        self.fractionLabel.setText(_translate("twoPhaseModelDryCaseDialog", "Concentration (%)"))
        self.label_2.setText(_translate("twoPhaseModelDryCaseDialog", "Min Diameter (mm)"))
        self.fractionDoubleSpinBox.setSuffix(_translate("twoPhaseModelDryCaseDialog", "%"))
        self.label_6.setText(_translate("twoPhaseModelDryCaseDialog", "Min Aspect Ratio"))
        self.label_7.setText(_translate("twoPhaseModelDryCaseDialog", "Max Aspect Ratio"))
        self.labelLabel.setText(_translate("twoPhaseModelDryCaseDialog", "Label"))

