# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\tomographysetup.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_tomographySetupDialog(object):
    def setupUi(self, tomographySetupDialog):
        tomographySetupDialog.setObjectName("tomographySetupDialog")
        tomographySetupDialog.resize(300, 430)
        tomographySetupDialog.setMinimumSize(QtCore.QSize(300, 430))
        tomographySetupDialog.setMaximumSize(QtCore.QSize(300, 430))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tomoSetup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tomographySetupDialog.setWindowIcon(icon)
        tomographySetupDialog.setWindowOpacity(1.0)
        self.buttonBox = QtWidgets.QDialogButtonBox(tomographySetupDialog)
        self.buttonBox.setGeometry(QtCore.QRect(80, 390, 230, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(tomographySetupDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 271, 129))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.projectionStepLabel = QtWidgets.QLabel(self.groupBox)
        self.projectionStepLabel.setObjectName("projectionStepLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.projectionStepLabel)
        self.projectionStepLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.projectionStepLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.projectionStepLineEdit.setObjectName("projectionStepLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.projectionStepLineEdit)
        self.diameterRingLabel = QtWidgets.QLabel(self.groupBox)
        self.diameterRingLabel.setObjectName("diameterRingLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.diameterRingLabel)
        self.diameterRingLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.diameterRingLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.diameterRingLineEdit.setObjectName("diameterRingLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.diameterRingLineEdit)
        self.oneProjectionLabel = QtWidgets.QLabel(self.groupBox)
        self.oneProjectionLabel.setObjectName("oneProjectionLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.oneProjectionLabel)
        self.oneProjectionCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.oneProjectionCheckBox.setObjectName("oneProjectionCheckBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.oneProjectionCheckBox)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.groupBox_2 = QtWidgets.QGroupBox(tomographySetupDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 275, 235))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName("formLayout")
        self.pointSourceLabel = QtWidgets.QLabel(self.groupBox_2)
        self.pointSourceLabel.setObjectName("pointSourceLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pointSourceLabel)
        self.pointSourceCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.pointSourceCheckBox.setObjectName("pointSourceCheckBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pointSourceCheckBox)
        self.transducerSizeLabel = QtWidgets.QLabel(self.groupBox_2)
        self.transducerSizeLabel.setObjectName("transducerSizeLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.transducerSizeLabel)
        self.transducerSizeLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.transducerSizeLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.transducerSizeLineEdit.setObjectName("transducerSizeLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.transducerSizeLineEdit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.previewPushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.previewPushButton.setMinimumSize(QtCore.QSize(0, 41))
        self.previewPushButton.setMaximumSize(QtCore.QSize(16777215, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/previewImage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previewPushButton.setIcon(icon1)
        self.previewPushButton.setIconSize(QtCore.QSize(24, 24))
        self.previewPushButton.setObjectName("previewPushButton")
        self.verticalLayout.addWidget(self.previewPushButton)
        self.advancedParametersSetupPushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.advancedParametersSetupPushButton.setMinimumSize(QtCore.QSize(0, 41))
        self.advancedParametersSetupPushButton.setMaximumSize(QtCore.QSize(16777215, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/simModel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.advancedParametersSetupPushButton.setIcon(icon2)
        self.advancedParametersSetupPushButton.setIconSize(QtCore.QSize(24, 24))
        self.advancedParametersSetupPushButton.setObjectName("advancedParametersSetupPushButton")
        self.verticalLayout.addWidget(self.advancedParametersSetupPushButton)
        self.signalSetupPushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.signalSetupPushButton.setMinimumSize(QtCore.QSize(0, 41))
        self.signalSetupPushButton.setMaximumSize(QtCore.QSize(16777215, 41))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/signal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signalSetupPushButton.setIcon(icon3)
        self.signalSetupPushButton.setIconSize(QtCore.QSize(24, 24))
        self.signalSetupPushButton.setCheckable(False)
        self.signalSetupPushButton.setDefault(False)
        self.signalSetupPushButton.setFlat(False)
        self.signalSetupPushButton.setObjectName("signalSetupPushButton")
        self.verticalLayout.addWidget(self.signalSetupPushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(tomographySetupDialog)
        self.buttonBox.accepted.connect(tomographySetupDialog.accept)
        self.buttonBox.rejected.connect(tomographySetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(tomographySetupDialog)

    def retranslateUi(self, tomographySetupDialog):
        _translate = QtCore.QCoreApplication.translate
        tomographySetupDialog.setWindowTitle(_translate("tomographySetupDialog", "Tomography Setup"))
        self.groupBox.setTitle(_translate("tomographySetupDialog", "Tomography Setup"))
        self.projectionStepLabel.setText(_translate("tomographySetupDialog", "Projection Step (º)"))
        self.diameterRingLabel.setText(_translate("tomographySetupDialog", "Diameter Ring (mm)"))
        self.oneProjectionLabel.setText(_translate("tomographySetupDialog", "One Projection"))
        self.groupBox_2.setTitle(_translate("tomographySetupDialog", "Transducer Setup"))
        self.pointSourceLabel.setText(_translate("tomographySetupDialog", "Point Source"))
        self.transducerSizeLabel.setText(_translate("tomographySetupDialog", "Transducer Size (mm)"))
        self.previewPushButton.setText(_translate("tomographySetupDialog", "Preview Transducer Setup"))
        self.advancedParametersSetupPushButton.setText(_translate("tomographySetupDialog", "Advanced Parameters Setup"))
        self.signalSetupPushButton.setText(_translate("tomographySetupDialog", "Signal Parameters"))

import SimNDT.gui.resources_rc

