# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\twophasemodelimmersioncase.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_twoPhaseModelImmersionCaseDialog(object):
    def setupUi(self, twoPhaseModelImmersionCaseDialog):
        twoPhaseModelImmersionCaseDialog.setObjectName("twoPhaseModelImmersionCaseDialog")
        twoPhaseModelImmersionCaseDialog.resize(476, 365)
        twoPhaseModelImmersionCaseDialog.setMaximumSize(QtCore.QSize(476, 365))
        twoPhaseModelImmersionCaseDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox = QtWidgets.QDialogButtonBox(twoPhaseModelImmersionCaseDialog)
        self.buttonBox.setGeometry(QtCore.QRect(90, 330, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(twoPhaseModelImmersionCaseDialog)
        self.frame.setGeometry(QtCore.QRect(20, 110, 441, 182))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 421, 162))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gradingDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.gradingDoubleSpinBox.setMinimum(0.01)
        self.gradingDoubleSpinBox.setMaximum(0.8)
        self.gradingDoubleSpinBox.setSingleStep(0.2)
        self.gradingDoubleSpinBox.setProperty("value", 0.1)
        self.gradingDoubleSpinBox.setObjectName("gradingDoubleSpinBox")
        self.gridLayout.addWidget(self.gradingDoubleSpinBox, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.labelSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.labelSpinBox.setMaximum(240)
        self.labelSpinBox.setSingleStep(40)
        self.labelSpinBox.setProperty("value", 80)
        self.labelSpinBox.setObjectName("labelSpinBox")
        self.gridLayout.addWidget(self.labelSpinBox, 1, 0, 1, 1)
        self.minAspectRatioDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.minAspectRatioDoubleSpinBox.setMinimum(0.2)
        self.minAspectRatioDoubleSpinBox.setMaximum(1.0)
        self.minAspectRatioDoubleSpinBox.setProperty("value", 0.5)
        self.minAspectRatioDoubleSpinBox.setObjectName("minAspectRatioDoubleSpinBox")
        self.gridLayout.addWidget(self.minAspectRatioDoubleSpinBox, 3, 2, 1, 1)
        self.minDiameterDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.minDiameterDoubleSpinBox.setMinimum(0.2)
        self.minDiameterDoubleSpinBox.setMaximum(20.0)
        self.minDiameterDoubleSpinBox.setSingleStep(0.1)
        self.minDiameterDoubleSpinBox.setProperty("value", 0.5)
        self.minDiameterDoubleSpinBox.setObjectName("minDiameterDoubleSpinBox")
        self.gridLayout.addWidget(self.minDiameterDoubleSpinBox, 0, 2, 1, 1)
        self.fractionLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.fractionLabel.setObjectName("fractionLabel")
        self.gridLayout.addWidget(self.fractionLabel, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.fractionDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.fractionDoubleSpinBox.setMinimum(0.1)
        self.fractionDoubleSpinBox.setMaximum(70.0)
        self.fractionDoubleSpinBox.setProperty("value", 10.0)
        self.fractionDoubleSpinBox.setObjectName("fractionDoubleSpinBox")
        self.gridLayout.addWidget(self.fractionDoubleSpinBox, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 3, 1, 1)
        self.maxDiameterDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.maxDiameterDoubleSpinBox.setMinimum(0.02)
        self.maxDiameterDoubleSpinBox.setMaximum(20.0)
        self.maxDiameterDoubleSpinBox.setSingleStep(0.1)
        self.maxDiameterDoubleSpinBox.setProperty("value", 10.0)
        self.maxDiameterDoubleSpinBox.setObjectName("maxDiameterDoubleSpinBox")
        self.gridLayout.addWidget(self.maxDiameterDoubleSpinBox, 1, 2, 1, 1)
        self.maxAspectRatioDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.maxAspectRatioDoubleSpinBox.setMinimum(0.3)
        self.maxAspectRatioDoubleSpinBox.setMaximum(1.0)
        self.maxAspectRatioDoubleSpinBox.setSingleStep(0.1)
        self.maxAspectRatioDoubleSpinBox.setProperty("value", 0.8)
        self.maxAspectRatioDoubleSpinBox.setObjectName("maxAspectRatioDoubleSpinBox")
        self.gridLayout.addWidget(self.maxAspectRatioDoubleSpinBox, 4, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 3, 1, 1)
        self.labelLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelLabel.setObjectName("labelLabel")
        self.gridLayout.addWidget(self.labelLabel, 1, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(twoPhaseModelImmersionCaseDialog)
        self.progressBar.setGeometry(QtCore.QRect(30, 300, 411, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.frame_2 = QtWidgets.QFrame(twoPhaseModelImmersionCaseDialog)
        self.frame_2.setGeometry(QtCore.QRect(20, 10, 441, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 411, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.boxWidthLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.boxWidthLineEdit.setObjectName("boxWidthLineEdit")
        self.gridLayout_2.addWidget(self.boxWidthLineEdit, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 3, 1, 1)
        self.boxHeightLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.boxHeightLineEdit.setObjectName("boxHeightLineEdit")
        self.gridLayout_2.addWidget(self.boxHeightLineEdit, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 1, 1, 1)
        self.circularSpecimenCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.circularSpecimenCheckBox.setObjectName("circularSpecimenCheckBox")
        self.gridLayout_2.addWidget(self.circularSpecimenCheckBox, 1, 2, 1, 2)
        self.matrixLabelSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.matrixLabelSpinBox.setMaximum(240)
        self.matrixLabelSpinBox.setSingleStep(40)
        self.matrixLabelSpinBox.setProperty("value", 40)
        self.matrixLabelSpinBox.setObjectName("matrixLabelSpinBox")
        self.gridLayout_2.addWidget(self.matrixLabelSpinBox, 1, 0, 1, 1)

        self.retranslateUi(twoPhaseModelImmersionCaseDialog)
        self.buttonBox.accepted.connect(twoPhaseModelImmersionCaseDialog.accept)
        self.buttonBox.rejected.connect(twoPhaseModelImmersionCaseDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(twoPhaseModelImmersionCaseDialog)

    def retranslateUi(self, twoPhaseModelImmersionCaseDialog):
        _translate = QtCore.QCoreApplication.translate
        twoPhaseModelImmersionCaseDialog.setWindowTitle(_translate("twoPhaseModelImmersionCaseDialog", "Two-Phase Model (Immersion Case)"))
        self.label_5.setText(_translate("twoPhaseModelImmersionCaseDialog", "Grading Curve Coeff"))
        self.label_4.setText(_translate("twoPhaseModelImmersionCaseDialog", "Max Diameter (mm)"))
        self.fractionLabel.setText(_translate("twoPhaseModelImmersionCaseDialog", "Concentration (%)"))
        self.label_2.setText(_translate("twoPhaseModelImmersionCaseDialog", "Min Diameter (mm)"))
        self.fractionDoubleSpinBox.setSuffix(_translate("twoPhaseModelImmersionCaseDialog", "%"))
        self.label_6.setText(_translate("twoPhaseModelImmersionCaseDialog", "Min Aspect Ratio"))
        self.label_7.setText(_translate("twoPhaseModelImmersionCaseDialog", "Max Aspect Ratio"))
        self.labelLabel.setText(_translate("twoPhaseModelImmersionCaseDialog", "Aggregates Label"))
        self.label.setText(_translate("twoPhaseModelImmersionCaseDialog", "Box Width (mm)"))
        self.label_3.setText(_translate("twoPhaseModelImmersionCaseDialog", "Box Height (mm)"))
        self.label_8.setText(_translate("twoPhaseModelImmersionCaseDialog", "Cement Matrix Label"))
        self.circularSpecimenCheckBox.setText(_translate("twoPhaseModelImmersionCaseDialog", "Circular Specimen"))

